site_name: Dariel Piñón 0369
site_description: Instalaciones y gestión de Ubuntu y Windows.
site_author: Dariel Piñón
site_url: https://daarieel.github.io/0369/

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Proyecto 1; Sistema Ubuntu Linux: 
      - Introducción: Proyecto1/introduccion.md
      - Sprint 1:
          - Instalación Máquina Virtual y Ubuntu: Proyecto1/Sprint1/instalacion.md
          - Configuración Básica de Red: Proyecto1/Sprint1/conf_red.md 
          - Instalación de Programas: Proyecto1/Sprint1/inst_programas.md 
          - Puntos de Restauración: Proyecto1/Sprint1/puntos_restauracion.md
          - Gestores de Arranque: Proyecto1/Sprint1/gestores_arranque.md
          - Recuperación del Gestor de Arranque: Proyecto1/Sprint1/rec_gest_arranque.md
          - Licencias: Proyecto1/Sprint1/licencias.md
      - Sprint 2:
          - Gestión de Usuarios y Grupos: Proyecto1/Sprint2/gest_usu.md
          - Gestión de Permisos: Proyecto1/Sprint2/gest_permisos.md
          - Sistema de Ficheros y Particiones: Proyecto1/Sprint2/sis_ficheros_particiones.md
          - Compartir Ficheros en Red: Proyecto1/Sprint2/comp_red.md
          - Cuotas de Disco: Proyecto1/Sprint2/disco.md
          - Gestión de Procesos: Proyecto1/Sprint2/gest_procesos.md
          - Copias de Seguridad: Proyecto1/Sprint2/copies_seguretat_auto.md
          - Automatización de Tareas: Proyecto1/Sprint2/auto_tareas.md
      - Sprint 3:
          - Dominios y LDAP: Proyecto1/Sprint3/dom_ldap.md
          - Unir Clientes al Dominio: Proyecto1/Sprint3/unir_cli.md
          - LDAP con Interfaz Gráfica: Proyecto1/Sprint3/ldap_gra.md
          - Gestión del Dominio: Proyecto1/Sprint3/gest_dom.md
          - NFS: Proyecto1/Sprint3/nfs.md
          - SAMBA: Proyecto1/Sprint3/samba.md
      - Sprint 4:
          - RAIDS: Proyecto1/Sprint4/raid.md
      - Sprint 5:
          - Monitorización: Proyecto1/Sprint5/monitorizacion.md
          - Auditorías de Seguridad: Proyecto1/Sprint5/auditorias.md
          - Servidor de Actualizaciones: Proyecto1/Sprint5/actualizaciones.md
  - Proyecto 2; Sistema Windows:
      - Introducción: Proyecto2/introduccion.md
      - Sprint 1:
          - Licencias: Proyecto2/Sprint1/licencias.md
          - Instalación Windows: Proyecto2/Sprint1/instalacion.md
          - Configuración de Red y Programas Base: Proyecto2/Sprint1/red_programas.md
          - Gestor de Arranque: Proyecto2/Sprint1/arranque.md
      - Sprint 2:
          - Quotas y Usuarios: Proyecto2/Sprint2/quotas.md
          - Copias de Seguridad y Automatización: Proyecto2/Sprint2/backup.md
          - Gestión de Procesos: Proyecto2/Sprint2/procesos.md
          - Gestión de ACLs: Proyecto2/Sprint2/acl.md
          
theme:
  name: "material"
  language: es
  palette:
    - scheme: slate  

copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://daarieel.github.io/0369">MkDocs 0369</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://github.com/daarieel">Dariel Piñón</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-flex;"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""></a></p>